### ISSUE TITLE
Build failed with the latest Gradle

### ISSUE THREAD

**Issue by almozavr** [inmite/android-validation-komensky#9]
```
   compile 'com.android.support:support-v4:+'
   compile 'eu.inmite.android.lib:android-validation-komensky:0.9.2'
```

will fail 'cause of

``` xml
<dependency>
    <groupId>com.google.android</groupId>
    <artifactId>support-v4</artifactId>
</dependency>
```

missing `provided`?
### Error:

```
Error:Execution failed for task ':apps:sample:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
    /Applications/Android Studio.app/android-sdk-macosx/build-tools/19.0.3/dx --dex ...

    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:594)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:552)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:533)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
        at com.android.dx.command.dexer.Main.run(Main.java:230)
        at com.android.dx.command.dexer.Main.main(Main.java:199)
        at com.android.dx.command.Main.main(Main.java:103)
```

**Comment by msevgi** [comment]
Thanks tomik-dev.
